version: "3"
services:
    app:
        build: .
        restart: always
        command: >
            bash -c "
                pip install -r requirements.txt &&
                python app.py
            "
        working_dir: /code
        ports: 
            - 127.0.0.1:18080:18080
        volumes:
            - .:/code
